<?php

namespace EntrepriseBundle\Repository;

/**
 * PlaningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaningRepository extends \Doctrine\ORM\EntityRepository
{
}
