<?php

namespace PaymentBundle\Repository;

/**
 * DetailJetonPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailJetonPackRepository extends \Doctrine\ORM\EntityRepository
{
}
