<?php

namespace PaymentBundle\Repository;

/**
 * JetonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JetonRepository extends \Doctrine\ORM\EntityRepository
{
}
