<?php

namespace ProfilBundle\Repository;

/**
 * dresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dresseRepository extends \Doctrine\ORM\EntityRepository
{
}
