<?php

namespace ProfilBundle\Repository;

/**
 * profilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profilRepository extends \Doctrine\ORM\EntityRepository
{
}
