<?php

namespace ProfilBundle\Repository;

/**
 * ProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProRepository extends \Doctrine\ORM\EntityRepository
{
}
