<?php

namespace ProfilBundle\Repository;

/**
 * RecommRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommRepository extends \Doctrine\ORM\EntityRepository
{
}
